### ISSUE TITLE
能详细讲讲为什么Stick To GCD (dispatch_barrier)是最好的解决方案？

### ISSUE THREAD

**Issue by jiangyancong** [SatanWoo/SatanWoo.github.io#2]
《从Immutable来谈谈对于线程安全的理解误区》文章写得很好，只是最后着笔的时候，没有详细展开为什么用dispatch_barrier是最好的解决方案。
dispatch_barrier 只是保证多个并发的dispatch的时候，能够保证时序性，应该解决的只是时序性问题吧？

另外，文章不能评论真的很蛋疼。。

**Comment by SatanWoo** [comment]
可以直接评论啊

**Comment by SatanWoo** [comment]
@jiangyancong 你需要点击文章标题去评论啊~

**Comment by jiangyancong** [comment]
啊，看到了，不好意思，业务不熟，呵呵，我评论了。
